services:
    skillaegis-editor:
        build: .
        container_name: skillaegis-editor
        image: skillaegis/editor:latest
        working_dir: /app
        environment:
            - SKILLAEGIS_HOST=0.0.0.0
            - SKILLAEGIS_PORT=4002
            - SKILLAEGIS_EXERCISE_FOLDER=scenarios
        volumes:
            - ./scenarios:/app/scenarios
        ports:
            - "4002:4002"
